### ISSUE TITLE
Test failing with DecisionTree v0.6.5+

### ISSUE THREAD

**Issue by bensadeghi** [ppalmes/CombineML.jl#13]
First off, thank you for maintaining this package, awesome work!!

There has been some [fruitful effort](https://github.com/bensadeghi/DecisionTree.jl/commit/9a12720d8a083751b715c93d454bd61d0baeec28) recently in improving the performance (in execution time and memory allocation) for the DecisionTree package, for both classification and regression, and we're now seeing 4-10x speed up. This has required a rewrite of the _split() functions, where now the splits and hence predictions aren't identical to those of DT v0.6.5.

As a result, one of the CombineML's tests ("Pipeline works with fixture data.") is now failing, and I'm having trouble isolating the issue.

Need your help and guidance in troubleshooting this failing test and getting CombineML onto the soon to be [DT v0.7.2](https://github.com/bensadeghi/DecisionTree.jl/releases/tag/v0.7.2)

To reproduce the test error, just pull from master: ```Pkg.checkout("DecisionTree")```

**Comment by ppalmes** [comment]
Thanks for the heads-up. I'll look into it.

**Comment by ppalmes** [comment]
I have an idea what causes it. The issue is in the one-hot-encoder pipeline. It has some inconsistency that causes different output from the hardcoded one. As a temporary solution, I'm listing the two possible outputs until it's fix.

**Comment by bensadeghi** [comment]
Thank you!!
