### ISSUE TITLE
IPYNB has issues

### ISSUE THREAD

**Issue by tlienart** [ppalmes/CombineML.jl#18]
When going through the notebook, there were several issues, some I could fix, some I could not. 

1. ~~use of `pipeline` is now prohibited (clashes with `Base`)~~
2. ~~the `RandomForest` should have `:num_subfeatures => 0` and not ` => nothing` afaiu~~
3. I could not run the Scikitlearn cell note that both `*_AVAILABLE` bools are false (maybe I didn't do something but couldn't find different way)

```
julia> CombineML.System.LIB_SKL_AVAILABLE
false
julia> CombineML.System.LIB_CRT_AVAILABLE
false
```

and so `SKLLearner` was not available. 

4. ~~use of `mean` must now be accompanied by `using Statistics`~~
5. I could not run `@parallel`, I'm assuming it comes from `using Distributed` but may have changed name

The fixes on the notebook: https://github.com/tlienart/CombineML.jl  , now in a PR fixing (1, 2, 4) #19

**Comment by ppalmes** [comment]
Thanks for pointing this out. Yes, I forgot to update the notebook. I'll update it this week including your changes. Maybe you can create a pull request?

**Comment by tlienart** [comment]
👍 the reason I had not was because I couldn't fix all the issues, also git modifs on notebooks are a pain but I've now opened one with the current fixes for (1, 2, 4) https://github.com/ppalmes/CombineML.jl/pull/19

**Comment by ppalmes** [comment]
this notebook has been rewritten to reflect the API changes.
