### ISSUE TITLE
pycall api update

### ISSUE THREAD

**Issue by stevengj** [ppalmes/CombineML.jl#20]
PyCall 1.90.0 is now released, which change `o[:foo]` and `o["foo"]` to `o.foo` and `o."foo"`, respectively, for python objects `o`; see also JuliaPy/PyCall.jl#629.

The old `getindex` methods still work but are deprecated, so you'll want to put out a new release that uses the new methods and REQUIREs PyCall 1.90.0 to avoid having zillions of deprecation messages.

**Comment by ppalmes** [comment]
I tried to use PyCall 1.90.0 but I get errors when I do ENS=pyimport("sklearn.ensemble") to replace @pyimport sklearn.ensemble as ENS. Any idea?

**Comment by ppalmes** [comment]
never mind. it seems a dependency issue in my scikit-learn installation.

**Comment by stevengj** [comment]
See https://github.com/JuliaPy/PyCall.jl#using-pycall-from-julia-modules about importing modules in a precompile-safe way.

**Comment by ppalmes** [comment]
finished upgrading to PyCall 1.90.0
